FROM ubuntu:latest

RUN apt-get update && apt-get -y install cmake
RUN apt-get -y install git
RUN apt-get -y install gfortran 
RUN git clone https://github.com/kurzepajedrzej/calculator.git
RUN apt-get -y install gcc
RUN apt -y install build-essential

WORKDIR "/calculator"
RUN cmake .
RUN make 
